[api_keys]
google = "AIzaSyDz2RHVQA64j_ZDtEp0CC4Qvkg3xKgsMEU"


#
#python3 -m venv .venv
#source .venv/bin/activate
#pip install streamlit pandas google-generativeai python-dotenv sqlalchemy bcrypt
#streamlit run app.py
